import Navbar from "@/components/header/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="w-full min-h-screen bg-gray-100">
          <div className="max-w-[1100px] mx-auto p-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
